export const SEED = {
  player: {
    id: '905b4d32-ee84-4d1d-8d88-2d14416cfab8',
    name: 'Andres Arias',
    team: 'Leo',
    position: 'Striker',
    league: 'Bad Doggies',
    agency: 'restricted',
  },
  team: [
    {
      id: '905b4d32-ee84-4d1d-8d88-2d14416cfab9',
      name: 'Leo',
      players: [
        {
          id: '905b4d32-ee84-4d1d-8d88-2d14416c1234',
          name: 'Leo Arias',
          team: 'Leo',
          position: 'Striker',
          league: 'Bad Doggies',
          agency: 'restricted',
        },
        {
          id: '905b4d32-ee84-4d1d-8d88-2d14416c567f',
          name: 'Andres Arias',
          team: 'Leo',
          position: 'Striker',
          league: 'Bad Doggies',
          agency: 'restricted',
        },
        {
          id: '905b4d32-ee84-4d1d-8d88-2d14416cdg4c',
          name: 'Casey Arias',
          team: 'Leo',
          position: 'Midfielder',
          league: 'Bad Doggies',
          agency: 'restricted',
        },
        {
          id: '905b4d32-ee84-4d1d-8d88-2d14416cgnye',
          name: 'Leela Arias',
          team: 'Leo',
          position: 'Midfielder',
          league: 'Bad Doggies',
          agency: 'restricted',
        },
        {
          id: '905b4d32-ee84-4d1d-8d88-2d14416cnl23',
          name: 'Fluffy',
          team: 'Leo',
          position: 'Defender',
          league: 'Bad Doggies',
          agency: 'restricted',
        },
        {
          id: '905b4d32-ee84-4d1d-8d88-2d14416cwpcs',
          name: 'Trevor',
          team: 'Leo',
          position: 'Defender',
          league: 'Bad Doggies',
          agency: 'restricted',
        },
      ],
      league: 'Bad Doggies',
      record: [2, 0],
    },
    {
      id: '905b4d32-ee84-4d1d-8d88-2d14416cfvac',
      name: 'Fluffly',
      players: [
        {
          id: '905b4d32-ee84-4d1d-8d88-2d14416cerfc',
          name: 'Fleo Farias',
          team: 'Fluffly',
          position: 'Striker',
          league: 'Killer Kitties',
          agency: 'restricted',
        },
        {
          id: '905b4d32-ee84-4d1d-8d88-2d14416c567f',
          name: 'Flandres Farias',
          team: 'Fluffly',
          position: 'Striker',
          league: 'Killer Kitties',
          agency: 'restricted',
        },
        {
          id: '905b4d32-ee84-4d1d-8d88-2d1nnc16cdg4c',
          name: 'Fasey Farias',
          team: 'Fluffly',
          position: 'Midfielder',
          league: 'Killer Kitties',
          agency: 'restricted',
        },
        {
          id: '905b4d32-ee84-4d1d-8d88-2d14416cghft',
          name: 'Fleela Farias',
          team: 'Fluffly',
          position: 'Midfielder',
          league: 'Killer Kitties',
          agency: 'restricted',
        },
        {
          id: '905b4d32-ee84-4d1d-8d88-2d14416cnnnn',
          name: 'Fluffy',
          team: 'Fluffly',
          position: 'Defender',
          league: 'Killer Kitties',
          agency: 'restricted',
        },
        {
          id: '905b4d32-ee84-4d1d-8d88-2d14416c33d',
          name: 'Trevor',
          team: 'Fluffly',
          position: 'Defender',
          league: 'Killer Kitties',
          agency: 'restricted',
        },
      ],
      league: 'Killer Kitties',
      record: [1, 1],
    },
    {
      id: '905b4d32-ee84-4d1d-8d88-2d14416cf333',
      name: 'The rotties',
      players: [
        {
          id: '905b4d32-ee84-4d1d-8d88-2d14416alss',
          name: 'Theo rotties',
          team: 'The rotties',
          position: 'Striker',
          league: 'Bad Doggies',
          agency: 'restricted',
        },
      ],
      league: 'Bad Doggies',
      record: [2, 0],
    },
    {
      id: '905b4d32-ee84-4d1d-8d88-2d14416cf101',
      name: 'Weiner Power',
      players: [
        {
          id: '905b4d32-ee84-4d1d-8d88-2d14416vvvv',
          name: 'Little Weiner',
          team: 'Weiner Power',
          position: 'Striker',
          league: 'Bad Doggies',
          agency: 'restricted',
        },
        {
          id: '905b4d32-ee84-4d1d-8d88-2d14416cnhnh',
          name: 'Big Weiner',
          team: 'Weiner Power',
          position: 'Striker',
          league: 'Bad Doggies',
          agency: 'restricted',
        },
      ],
      league: 'Bad Doggies',
      record: [2, 0],
    },
    {
      id: '905b4d32-ee84-4d1d-8d88-2d14416llll',
      name: 'Flying Bunnies',
      players: [
        {
          id: '905b4d32-ee84-4d1d-8d88-2d14416cerfc',
          name: 'Bunny Ed',
          team: 'Flying Bunnies',
          position: 'Striker',
          league: 'Killer Kitties',
          agency: 'restricted',
        },
        {
          id: '905b4d32-ee84-4d1d-8d88-2d14416c567f',
          name: 'Bunny Alfred',
          team: 'Flying Bunnies',
          position: 'Striker',
          league: 'Killer Kitties',
          agency: 'restricted',
        },
        {
          id: '905b4d32-ee84-4d1d-8d88-2d1nnc16cdg4c',
          name: 'Bunny Fred',
          team: 'Flying Bunnies',
          position: 'Midfielder',
          league: 'Killer Kitties',
          agency: 'restricted',
        },
      ],
      league: 'Killer Kitties',
      record: [0, 2],
    },
  ],
  leagues: [
    {
      id: '905b4d32-ee84-4d1d-8d88-2d14416c0000',
      name: 'Bad Doggies',
      teams: [
        {
          id: '905b4d32-ee84-4d1d-8d88-2d14416cfab9',
          name: 'Leo',
          players: [
            {
              id: '905b4d32-ee84-4d1d-8d88-2d14416c1234',
              name: 'Leo Arias',
              team: 'Leo',
              position: 'Striker',
              league: 'Bad Doggies',
              agency: 'restricted',
            },
            {
              id: '905b4d32-ee84-4d1d-8d88-2d14416c567f',
              name: 'Andres Arias',
              team: 'Leo',
              position: 'Striker',
              league: 'Bad Doggies',
              agency: 'restricted',
            },
            {
              id: '905b4d32-ee84-4d1d-8d88-2d14416cdg4c',
              name: 'Casey Arias',
              team: 'Leo',
              position: 'Midfielder',
              league: 'Bad Doggies',
              agency: 'restricted',
            },
            {
              id: '905b4d32-ee84-4d1d-8d88-2d14416cgnye',
              name: 'Leela Arias',
              team: 'Leo',
              position: 'Midfielder',
              league: 'Bad Doggies',
              agency: 'restricted',
            },
            {
              id: '905b4d32-ee84-4d1d-8d88-2d14416cnl23',
              name: 'Fluffy',
              team: 'Leo',
              position: 'Defender',
              league: 'Bad Doggies',
              agency: 'restricted',
            },
            {
              id: '905b4d32-ee84-4d1d-8d88-2d14416cwpcs',
              name: 'Trevor',
              team: 'Leo',
              position: 'Defender',
              league: 'Bad Doggies',
              agency: 'restricted',
            },
          ],
          league: 'Bad Doggies',
          record: [2, 0],
        },
        {
          id: '905b4d32-ee84-4d1d-8d88-2d14416cf333',
          name: 'The rotties',
          players: [
            {
              id: '905b4d32-ee84-4d1d-8d88-2d14416alss',
              name: 'Theo rotties',
              team: 'The rotties',
              position: 'Striker',
              league: 'Bad Doggies',
              agency: 'restricted',
            },
          ],
          league: 'Bad Doggies',
          record: [2, 0],
        },
        {
          id: '905b4d32-ee84-4d1d-8d88-2d14416cf101',
          name: 'Weiner Power',
          players: [
            {
              id: '905b4d32-ee84-4d1d-8d88-2d14416vvvv',
              name: 'Little Weiner',
              team: 'Weiner Power',
              position: 'Striker',
              league: 'Bad Doggies',
              agency: 'restricted',
            },
            {
              id: '905b4d32-ee84-4d1d-8d88-2d14416cnhnh',
              name: 'Big Weiner',
              team: 'Weiner Power',
              position: 'Striker',
              league: 'Bad Doggies',
              agency: 'restricted',
            },
          ],
          league: 'Bad Doggies',
          record: [2, 0],
        },
      ],
    },
    {
      id: '905b4d32-ee84-4d1d-8d88-2d14416c0001',
      name: 'Killer Kitties',
      teams: [
        {
          id: '905b4d32-ee84-4d1d-8d88-2d14416cfvac',
          name: 'Fluffly',
          players: [
            {
              id: '905b4d32-ee84-4d1d-8d88-2d14416cerfc',
              name: 'Fleo Farias',
              team: 'Fluffly',
              position: 'Striker',
              league: 'Killer Kitties',
              agency: 'restricted',
            },
            {
              id: '905b4d32-ee84-4d1d-8d88-2d14416c567f',
              name: 'Flandres Farias',
              team: 'Fluffly',
              position: 'Striker',
              league: 'Killer Kitties',
              agency: 'restricted',
            },
            {
              id: '905b4d32-ee84-4d1d-8d88-2d1nnc16cdg4c',
              name: 'Fasey Farias',
              team: 'Fluffly',
              position: 'Midfielder',
              league: 'Killer Kitties',
              agency: 'restricted',
            },
            {
              id: '905b4d32-ee84-4d1d-8d88-2d14416cghft',
              name: 'Fleela Farias',
              team: 'Fluffly',
              position: 'Midfielder',
              league: 'Killer Kitties',
              agency: 'restricted',
            },
            {
              id: '905b4d32-ee84-4d1d-8d88-2d14416cnnnn',
              name: 'Fluffy',
              team: 'Fluffly',
              position: 'Defender',
              league: 'Killer Kitties',
              agency: 'restricted',
            },
            {
              id: '905b4d32-ee84-4d1d-8d88-2d14416c33d',
              name: 'Trevor',
              team: 'Fluffly',
              position: 'Defender',
              league: 'Killer Kitties',
              agency: 'restricted',
            },
          ],
          league: 'Killer Kitties',
          record: [1, 1],
        },
        {
          id: '905b4d32-ee84-4d1d-8d88-2d14416llll',
          name: 'Flying Bunnies',
          players: [
            {
              id: '905b4d32-ee84-4d1d-8d88-2d14416cerfc',
              name: 'Bunny Ed',
              team: 'Flying Bunnies',
              position: 'Striker',
              league: 'Killer Kitties',
              agency: 'restricted',
            },
            {
              id: '905b4d32-ee84-4d1d-8d88-2d14416c567f',
              name: 'Bunny Alfred',
              team: 'Flying Bunnies',
              position: 'Striker',
              league: 'Killer Kitties',
              agency: 'restricted',
            },
            {
              id: '905b4d32-ee84-4d1d-8d88-2d1nnc16cdg4c',
              name: 'Bunny Fred',
              team: 'Flying Bunnies',
              position: 'Midfielder',
              league: 'Killer Kitties',
              agency: 'restricted',
            },
          ],
          league: 'Killer Kitties',
          record: [0, 2],
        },
      ],
    },
  ],
};

export const FREE_AGENT = [
  {
    id: '905b4d32-ee84-4d1d-8d88-2d14416c33d',
    name: 'Lionel Messi',
    team: '',
    position: 'striker',
    league: '',
    agency: 'freeAgent',
  },
  {
    id: '905b4d32-ee84-4d1d-8d88-2d144192837',
    name: 'Kylian Mbappé',
    team: '',
    position: 'striker',
    league: '',
    agency: 'freeAgent',
  },
  {
    id: '905b4d32-ee84-4d1d-8d88-2d144anvj38',
    name: 'Vinícius Júnior',
    team: '',
    position: 'left winger',
    league: '',
    agency: 'freeAgent',
  },
];
